language: cpp
dist: xenial

services:
  - docker
  
before_install:
  - docker build -t numpgsql/test .
  
script:    
  - docker run -e CODECOV_TOKEN  --user postgres numpgsql/test /bin/bash  -c "/usr/lib/postgresql/11/bin/initdb; /usr/lib/postgresql/11/bin/pg_ctl -D /var/lib/postgresql/data start ; cd /build/numpgsql; make installcheck; lcov --directory . --capture --output-file coverage.info; lcov --remove coverage.info '/usr/*' --output-file coverage.info; lcov --list coverage.info; bash <(curl -s https://codecov.io/bash) -f coverage.info || echo 'Codecov did not collect coverage reports'"

